version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./user-service:/var/www/html
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
    networks:
      - microservices-net

  product-service:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./product-service:/var/www/html
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq
    networks:
      - microservices-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management interface port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
    name: microservices-net

volumes:
  rabbitmq_data:
